test_is_empty = [
    ("[empty]", True),
    ("[-infinity,+infinity]", False),
    ("[1.0,2.0]", False),
    ("[-1.0,2.0]", False),
    ("[-3.0,-2.0]", False),
    ("[-infinity,2.0]", False),
    ("[-infinity,0.0]", False),
    ("[-infinity,-0.0]", False),
    ("[0.0,infinity]", False),
    ("[-0.0,infinity]", False),
    ("[-0.0,0.0]", False),
    ("[0.0,-0.0]", False),
    ("[0.0,0.0]", False),
    ("[-0.0,-0.0]", False),
]

test_is_empty_dec = [
    ("[nai]", False),
    ("[empty]_trv", True),
    ("[-infinity,+infinity]_def", False),
    ("[1.0,2.0]_com", False),
    ("[-1.0,2.0]_trv", False),
    ("[-3.0,-2.0]_dac", False),
    ("[-infinity,2.0]_trv", False),
    ("[-infinity,0.0]_trv", False),
    ("[-infinity,-0.0]_trv", False),
    ("[0.0,infinity]_def", False),
    ("[-0.0,infinity]_trv", False),
    ("[-0.0,0.0]_com", False),
    ("[0.0,-0.0]_trv", False),
    ("[0.0,0.0]_trv", False),
    ("[-0.0,-0.0]_trv", False),
]

test_is_entire = [
    ("[empty]", False),
    ("[-infinity,+infinity]", True),
    ("[1.0,2.0]", False),
    ("[-1.0,2.0]", False),
    ("[-3.0,-2.0]", False),
    ("[-infinity,2.0]", False),
    ("[-infinity,0.0]", False),
    ("[-infinity,-0.0]", False),
    ("[0.0,infinity]", False),
    ("[-0.0,infinity]", False),
    ("[-0.0,0.0]", False),
    ("[0.0,-0.0]", False),
    ("[0.0,0.0]", False),
    ("[-0.0,-0.0]", False),
]

test_is_entire_dec = [
    ("[nai]", False),
    ("[empty]_trv", False),
    ("[-infinity,+infinity]_trv", True),
    ("[-infinity,+infinity]_def", True),
    ("[-infinity,+infinity]_dac", True),
    ("[1.0,2.0]_com", False),
    ("[-1.0,2.0]_trv", False),
    ("[-3.0,-2.0]_dac", False),
    ("[-infinity,2.0]_trv", False),
    ("[-infinity,0.0]_trv", False),
    ("[-infinity,-0.0]_trv", False),
    ("[0.0,infinity]_def", False),
    ("[-0.0,infinity]_trv", False),
    ("[-0.0,0.0]_com", False),
    ("[0.0,-0.0]_trv", False),
    ("[0.0,0.0]_trv", False),
    ("[-0.0,-0.0]_trv", False),
]

test_is_common = [
    ("[-27.0,-27.0]", True),
    ("[-27.0, 0.0]", True),
    ("[0.0,0.0]", True),
    ("[-0.0,-0.0]", True),
    ("[-0.0,0.0]", True),
    ("[0.0,-0.0]", True),
    ("[5.0, 12.4]", True),
    ("[-0x1.FFFFFFFFFFFFFp1023, 0x1.FFFFFFFFFFFFFp1023]", True),
    ("[entire]", False),
    ("[empty]", False),
    ("[-infinity, 0.0]", False),
    ("[0.0, infinity]", False),
]

test_is_common_dec = [
    ("[-27.0,-27.0]_com", True),
    ("[-27.0, 0.0]_com", True),
    ("[0.0,0.0]_com", True),
    ("[-0.0,-0.0]_com", True),
    ("[-0.0,0.0]_com", True),
    ("[0.0,-0.0]_com", True),
    ("[5.0, 12.4]_com", True),
    ("[-0x1.FFFFFFFFFFFFFp1023, 0x1.FFFFFFFFFFFFFp1023]_com", True),
    ("[-27.0,-27.0]_trv", True),
    ("[-27.0, 0.0]_def", True),
    ("[0.0,0.0]_dac", True),
    ("[-0.0,-0.0]_trv", True),
    ("[-0.0,0.0]_def", True),
    ("[0.0,-0.0]_dac", True),
    ("[5.0, 12.4]_def", True),
    ("[-0x1.FFFFFFFFFFFFFp1023, 0x1.FFFFFFFFFFFFFp1023]_trv", True),
    ("[entire]_dac", False),
    ("[nai]", False),
    ("[empty]_trv", False),
    ("[-infinity, 0.0]_trv", False),
    ("[0.0, infinity]_def", False),
]

test_is_singleton = [
    ("[-27.0,-27.0]", True),
    ("[-2.0, -2.0]", True),
    ("[12.0,12.0]", True),
    ("[-0.0,-0.0]", True),
    ("[0.0,0.0]", True),
    ("[-0.0, 0.0]", True),
    ("[0.0, -0.0]", True),
    ("[empty]", False),
    ("[entire]", False),
    ("[-1.0, 0.0]", False),
    ("[-1.0, -0.5]", False),
    ("[1.0, 2.0]", False),
    ("[-infinity,-0x1.FFFFFFFFFFFFFp1023]", False),
    ("[-1.0,infinity]", False),
]

test_is_singleton_dec = [
    ("[-27.0,-27.0]_def", True),
    ("[-2.0, -2.0]_trv", True),
    ("[12.0,12.0]_dac", True),
    ("[-0.0,-0.0]_def", True),
    ("[0.0,0.0]_com", True),
    ("[-0.0, 0.0]_def", True),
    ("[0.0, -0.0]_dac", True),
    ("[empty]_trv", False),
    ("[nai]", False),
    ("[entire]_def", False),
    ("[-1.0, 0.0]_dac", False),
    ("[-1.0, -0.5]_com", False),
    ("[1.0, 2.0]_def", False),
    ("[-infinity,-0x1.FFFFFFFFFFFFFp1023]_dac", False),
    ("[-1.0,infinity]_trv", False),
]
